
const state={bank:[],filtered:[],current:0,score:0,streak:0,correct:0,wrong:0,timer:null,timeLeft:20,selected:[],review:[]};
const $=id=>document.getElementById(id);const els={filterYear:$('filterYear'),filterSubject:$('filterSubject'),filterDifficulty:$('filterDifficulty'),filterCount:$('filterCount'),qCount:$('qCount'),quizCount:$('quizCount'),quizPanel:$('quizPanel'),setupPanel:$('setupPanel'),resultPanel:$('resultPanel'),titlePill:$('titlePill'),metaPills:$('metaPills'),progressBar:document.querySelector('.progress > div'),timer:$('timer'),question:$('question'),answers:$('answers'),explanation:$('explanation'),nextBtn:$('nextBtn'),scoreNow:$('scoreNow'),resultScore:$('resultScore'),resultStats:$('resultStats'),reviewList:$('reviewList'),totalBank:$('totalBank')};
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
async function init(){const res=await fetch('data/questions.json');state.bank=await res.json();els.totalBank.textContent=state.bank.length;updateBankCount();}
function updateBankCount(){let f=[...state.bank];if(els.filterYear.value!=='all')f=f.filter(q=>q.year===els.filterYear.value);if(els.filterSubject.value!=='all')f=f.filter(q=>q.subject===els.filterSubject.value);if(els.filterDifficulty.value!=='all')f=f.filter(q=>q.difficulty===els.filterDifficulty.value);state.filtered=f;els.qCount.textContent=f.length;}
function startQuiz(){updateBankCount();const count=Number(els.filterCount.value||10);state.selected=shuffle(state.filtered).slice(0,Math.min(count,state.filtered.length));state.current=0;state.score=0;state.streak=0;state.correct=0;state.wrong=0;state.review=[];if(!state.selected.length){alert('Aucune question pour ce filtre.');return;}els.setupPanel.classList.add('hidden');els.resultPanel.classList.add('hidden');els.quizPanel.classList.remove('hidden');renderQuestion();}
function renderQuestion(){clearInterval(state.timer);const q=state.selected[state.current];els.quizCount.textContent=`${state.current+1} / ${state.selected.length}`;els.titlePill.textContent=`${q.subject} ${q.year}`;els.metaPills.innerHTML=`<span class="pill">${q.chapter}</span><span class="pill">${q.lesson}</span><span class="pill">${q.difficulty}</span><span class="pill">Score : ${state.score}</span>`;els.progressBar.style.width=`${(state.current/state.selected.length)*100}%`;els.question.textContent=q.prompt;els.answers.innerHTML='';els.explanation.classList.add('hidden');els.explanation.innerHTML='';els.nextBtn.classList.add('hidden');q.choices.forEach((choice,idx)=>{const btn=document.createElement('button');btn.className='answer';btn.innerHTML=`<strong>${String.fromCharCode(65+idx)}.</strong> ${choice}`;btn.onclick=()=>revealAnswer(idx);els.answers.appendChild(btn)});state.timeLeft=20;els.timer.textContent=`${state.timeLeft}s`;state.timer=setInterval(()=>{state.timeLeft--;els.timer.textContent=`${state.timeLeft}s`;if(state.timeLeft<=0){clearInterval(state.timer);revealAnswer(-1)}},1000)}
function revealAnswer(selectedIdx){clearInterval(state.timer);const q=state.selected[state.current];const buttons=[...document.querySelectorAll('.answer')];buttons.forEach((btn,idx)=>{btn.disabled=true;if(idx===q.answer)btn.classList.add('correct');if(selectedIdx===idx&&idx!==q.answer)btn.classList.add('wrong')});let gained=0;if(selectedIdx===q.answer){state.correct++;state.streak++;gained=100+(state.timeLeft*5)+(state.streak>=2?25:0);state.score+=gained}else{state.wrong++;state.streak=0;state.review.push({prompt:q.prompt,yourAnswer:selectedIdx>=0?q.choices[selectedIdx]:'Temps écoulé',goodAnswer:q.choices[q.answer],explanation:q.explanation})}els.scoreNow.textContent=state.score;els.explanation.classList.remove('hidden');const ok=selectedIdx===q.answer;els.explanation.innerHTML=`<strong>${ok?'Bonne réponse ✅':'Réponse correcte ❌'}</strong><br>${q.choices[q.answer]}<br><br><strong>Explication :</strong> ${q.explanation}${ok?`<br><br><strong>Points gagnés :</strong> ${gained}`:''}`;els.nextBtn.classList.remove('hidden');els.progressBar.style.width=`${((state.current+1)/state.selected.length)*100}%`;}
function nextQuestion(){state.current++;if(state.current>=state.selected.length)finishQuiz();else renderQuestion();}
function finishQuiz(){els.quizPanel.classList.add('hidden');els.resultPanel.classList.remove('hidden');els.resultScore.textContent=state.score;els.resultStats.innerHTML=`<div class="small">Bonnes réponses</div><div><strong>${state.correct}</strong></div><div class="small">Erreurs / temps écoulé</div><div><strong>${state.wrong}</strong></div><div class="small">Taux de réussite</div><div><strong>${Math.round((state.correct/state.selected.length)*100)}%</strong></div>`;els.reviewList.innerHTML='';if(state.review.length===0){els.reviewList.innerHTML='<div class="review-item"><strong>Parfait :</strong> aucune erreur à revoir 🎉</div>'}else{state.review.forEach(item=>{const div=document.createElement('div');div.className='review-item';div.innerHTML=`<div><strong>${item.prompt}</strong></div><div class="small">Ta réponse : ${item.yourAnswer}</div><div class="small">Bonne réponse : ${item.goodAnswer}</div><div>${item.explanation}</div>`;els.reviewList.appendChild(div)})}}
$('startBtn').onclick=startQuiz;$('restartBtn').onclick=()=>{els.resultPanel.classList.add('hidden');els.setupPanel.classList.remove('hidden');updateBankCount();};$('nextBtn').onclick=nextQuestion;['change','input'].forEach(evt=>{els.filterYear.addEventListener(evt,updateBankCount);els.filterSubject.addEventListener(evt,updateBankCount);els.filterDifficulty.addEventListener(evt,updateBankCount);els.filterCount.addEventListener(evt,updateBankCount);});if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}init();
